.TH MYSTRLEN 3 "September 2025" "libmyutils" "Library Functions"
.SH NAME
mystrlen \- calculate the length of a string
.SH SYNOPSIS
.B int mystrlen(const char* s);
.SH DESCRIPTION
The
.B mystrlen()
function returns the length of the string \fIs\fR, excluding the terminating null byte.
This is a custom implementation of the standard strlen function.
.SH RETURN VALUE
Returns the number of characters in the string on success.
.SH ERRORS
No errors are defined.
.SH AUTHOR
Written by Uzair.
